### ISSUE TITLE
Griffpatch's version

### ISSUE THREAD

**Issue by thecoder876** [ScratchAddons/DevtoolsExtension#1]
@WorldLanguages Since the devtools extension in SA is just @griffpatch's original extension, I think all that needs to be done is for their code to be imported. But I don't really think there's a point of this repo because of that. Still, I've attached the zip file with the extension code.
[Scratch3-Dev-Tools-master.zip](https://github.com/ScratchAddons/DevtoolsExtension/files/5802760/Scratch3-Dev-Tools-master.zip)

**Comment by WorldLanguages** [comment]
> the devtools extension in SA is just @griffpatch's original extension

That is incorrect, back in September it was, but the addon was updated (bug fixes, better performance, more features) while the extension hasn't.
Also, Griffpatch's extension lacks localization - we aim to provide Scratch Addons provided translations to the extension as well.
